# Site settings
title: Nyla Worker Personal Website
email: 
description: "Stuff I've done"
baseurl: ""
url: "http://nylaworker.github.io"
twitter_username: nyla_worker
github_username:  NylaWorker

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
